sudo: required
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  matrix:
    - PROJECT="dreg_estimators"
    - PROJECT="edward2_autoreparam"
    - PROJECT="graph_embedding/watch_your_step"
    - PROJECT="large_margin"
    - PROJECT="probabilistic_vqvae"
    - PROJECT="sufficient_input_subsets"
    - PROJECT="attribution"

install:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade flake8 virtualenv
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --ignore=E111,E114 --max-complexity=10 --max-line-length=127 --statistics
script:
  - ./$PROJECT/run.sh
