os: linux
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  jobs:
    - PROJECT="abps"
    - PROJECT="albert"
    - PROJECT="algae_dice"
    - PROJECT="attribution"
    - PROJECT="amortized_bo"
    - PROJECT="axial"
    - PROJECT="bam"
    - PROJECT="bisimulation_aaai2020"
    - PROJECT="bitempered_loss"
    - PROJECT="cell_mixer"
    - PROJECT="cfq"
    - PROJECT="cnn_quantization"
    - PROJECT="dataset_analysis"
    - PROJECT="dense_representations_for_entity_retrieval"
    - PROJECT="depth_from_video_in_the_wild"
    - PROJECT="dql_grasping"
    - PROJECT="dreg_estimators"
    - PROJECT="dual_pixels"
    - PROJECT="dvrl"
    - PROJECT="evanet"
    - PROJECT="explaining_risk_increase"
    - PROJECT="extrapolation"
    - PROJECT="fat"
    - PROJECT="flax_cifar"
    - PROJECT="generalized_rates"
    - PROJECT="genomics_ood"
    - PROJECT="graph_embedding/slaq"
    - PROJECT="graph_embedding/watch_your_step"
    - PROJECT="grouptesting"
    - PROJECT="hmc_swindles"
    - PROJECT="igt_optimizer"
    - PROJECT="large_margin"
    - PROJECT="learnreg"
    - PROJECT="learning_parameter_allocation"
    - PROJECT="local_implicit_grid"
    - PROJECT="m_theory"
    - PROJECT="meta_reward_learning/semantic_parsing"
    - PROJECT="meta_reward_learning/textworld"
    - PROJECT="moew"
    - PROJECT="moment_advice"
    - PROJECT="neutra"
    - PROJECT="neural_additive_models"
    - PROJECT="nigt_optimizer"
    - PROJECT="non_semantic_speech_benchmark"
    - PROJECT="norml"
    - PROJECT="opt_list"
    - PROJECT="poem"
    - PROJECT="protein_lm"
    - PROJECT="probabilistic_vqvae"
    - PROJECT="property_linking"
    - PROJECT="protoattend"
    - PROJECT="psycholab"
    - PROJECT="rl4circopt"
    - PROJECT="rllim"
    - PROJECT="robust_loss"
    - PROJECT="scrna_benchmark"
    - PROJECT="sm3"
    - PROJECT="soft_sort"
    - PROJECT="solver1d"
    - PROJECT="stacked_capsule_autoencoders"
    - PROJECT="state_of_sparsity"
    - PROJECT="stochastic_to_deterministic"
    - PROJECT="storm_optimizer"
    - PROJECT="strategic_exploration"
    - PROJECT="sufficient_input_subsets"
    - PROJECT="t5_closed_book_qa"
    - PROJECT="tabnet"
    - PROJECT="tcc"
    - PROJECT="towards_gan_benchmarks"
    - PROJECT="truss_decomposition"
    - PROJECT="towards_gan_benchmarks"
    - PROJECT="uflow"
    - PROJECT="wiki_split_bleu_eval"
    - PROJECT="wt5"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
script:
  - ./$PROJECT/run.sh

