language: python
git:
  depth: 10
  quiet: true
matrix:
  include:
    - env: PROJECT="attribution"
    - env: PROJECT="bam"
    - env: PROJECT="bitempered_loss"
    - env: PROJECT="cnn_quantization"
    - env: PROJECT="depth_from_video_in_the_wild"
    - env: PROJECT="dql_grasping"
    - env: PROJECT="dreg_estimators"
    - env: PROJECT="edward2_autoreparam"
    - env: PROJECT="explaining_risk_increase"
    - env: PROJECT="extrapolation"
    - env: PROJECT="fat"
    - env: PROJECT="genomics_ood"
    - env: PROJECT="graph_embedding/watch_your_step"
    - env: PROJECT="large_margin"
    - env: PROJECT="learnreg"
    - env: PROJECT="m_theory"
    - env: PROJECT="meta_reward_learning/semantic_parsing"
    - env: PROJECT="meta_reward_learning/textworld"
    - env: PROJECT="moew"
    - env: PROJECT="neutra"
    - env: PROJECT="norml"
    - env: PROJECT="probabilistic_vqvae"
    - env: PROJECT="psycholab"
    - env: PROJECT="robust_loss"
    - env: PROJECT="solver1d"
    - env: PROJECT="state_of_sparsity"
    - env: PROJECT="sufficient_input_subsets"
    - env: PROJECT="tcc"
    - env: PROJECT="towards_gan_benchmarks"
    - env: PROJECT="wiki_split_bleu_eval"
  allow_failures:  # TODO: Fix each project's tests and remove from this list
    - env: PROJECT="attribution"
    - env: PROJECT="bam"
    - env: PROJECT="bitempered_loss"
    - env: PROJECT="depth_from_video_in_the_wild"
    - env: PROJECT="fat"
    - env: PROJECT="genomics_ood"
    - env: PROJECT="m_theory"
    - env: PROJECT="norml"
    - env: PROJECT="probabilistic_vqvae"
    - env: PROJECT="psycholab"
    - env: PROJECT="tcc"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
script:
  - ./$PROJECT/run.sh
