os: linux
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  jobs:
    - PROJECT="abps"
    - PROJECT="adaptive_learning_rate_tuner"
    - PROJECT="albert"
    - PROJECT="after_kernel"
    - PROJECT="attribution"
    - PROJECT="amortized_bo"
    - PROJECT="assemblenet"
    - PROJECT="automatic_structured_vi"
    - PROJECT="axial"
    - PROJECT="bam"
    - PROJECT="bisimulation_aaai2020"
    - PROJECT="bitempered_loss"
    - PROJECT="cascaded_networks"
    - PROJECT="cell_mixer"
    - PROJECT="cfq"
    - PROJECT="cnn_quantization"
    - PROJECT="cola"
    - PROJECT="isolating_factors"
    - PROJECT="dataset_analysis"
    - PROJECT="dense_representations_for_entity_retrieval"
    - PROJECT="depth_and_motion_learning"
    - PROJECT="depth_from_video_in_the_wild"
    - PROJECT="docent"
    - PROJECT="dql_grasping"
    - PROJECT="dreg_estimators"
    - PROJECT="dual_pixels"
    - PROJECT="dvrl"
    - PROJECT="etcmodel"
    - PROJECT="evanet"
    - PROJECT="explaining_risk_increase"
    - PROJECT="extrapolation"
    - PROJECT="factorize_a_city"
    - PROJECT="fat"
    - PROJECT="flax_models/bert"
    - PROJECT="flax_models/cifar"
    - PROJECT="flax_models/moco"
    - PROJECT="f_net"
    - PROJECT="generalized_rates"
    - PROJECT="genomics_ood"
    - PROJECT="gfsa"
    - PROJECT="graph_embedding/dmon"
    - PROJECT="graph_embedding/slaq"
    - PROJECT="graph_embedding/watch_your_step"
    - PROJECT="hmc_swindles"
    - PROJECT="igt_optimizer"
    - PROJECT="implicit_constrained_optimization"
    - PROJECT="implicit_pdf"
    - PROJECT="jax_dft"
    - PROJECT="large_margin"
    - PROJECT="latent_programmer"
    - PROJECT="learn_to_infer"
    - PROJECT="keypose"
    - PROJECT="learnreg"
    - PROJECT="learning_parameter_allocation"
    - PROJECT="local_implicit_grid"
    - PROJECT="m_theory"
    - PROJECT="meta_reward_learning/semantic_parsing"
    - PROJECT="meta_reward_learning/textworld"
    - PROJECT="moew"
    - PROJECT="moment_advice"
    - PROJECT="muzero"
    - PROJECT="neutra"
    - PROJECT="neural_additive_models"
    - PROJECT="nigt_optimizer"
    - PROJECT="non_semantic_speech_benchmark"
    - PROJECT="norml"
    - PROJECT="numbert"
    - PROJECT="opt_list"
    - PROJECT="poem"
    - PROJECT="protein_lm"
    - PROJECT="probabilistic_vqvae"
    - PROJECT="property_linking"
    - PROJECT="protoattend"
    - PROJECT="proxy_rewards"
    - PROJECT="psycholab"
    - PROJECT="quantum_sample_learning"
    - PROJECT="realformer"
    - PROJECT="rl4circopt"
    - PROJECT="rllim"
    - PROJECT="robust_loss"
    - PROJECT="robust_loss_jax"
    - PROJECT="robust_optim"
    - PROJECT="routing_transformer"
    - PROJECT="scrna_benchmark"
    - PROJECT="single_view_mpi"
    - PROJECT="sm3"
    - PROJECT="smug_saliency"
    - PROJECT="social_rl"
    - PROJECT="soft_sort"
    - PROJECT="solver1d"
    - PROJECT="stacked_capsule_autoencoders"
    - PROJECT="state_of_sparsity"
    - PROJECT="stochastic_to_deterministic"
    - PROJECT="storm_optimizer"
    - PROJECT="strategic_exploration"
    - PROJECT="structformer"
    - PROJECT="student_mentor_data_cleaning"
    - PROJECT="sufficient_input_subsets"
    - PROJECT="t5_closed_book_qa"
    - PROJECT="tabnet"
    - PROJECT="tcc"
    - PROJECT="tf3d"
    - PROJECT="tiny_video_nets"
    - PROJECT="towards_gan_benchmarks"
    - PROJECT="truss_decomposition"
    - PROJECT="towards_gan_benchmarks"
    - PROJECT="uflow"
    - PROJECT="vdvae_flax"
    - PROJECT="visual_relationship"
    - PROJECT="wiki_split_bleu_eval"
    - PROJECT="wt5"
    - PROJECT="yoto"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
script:
  - ./$PROJECT/run.sh

