sudo: required
dist: trusty
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  matrix:
    - PROJECT="meta_reward_learning/textworld"
    - PROJECT="meta_reward_learning/semantic_parsing"
    - PROJECT="dreg_estimators"
    - PROJECT="edward2_autoreparam"
    - PROJECT="graph_embedding/watch_your_step"
    - PROJECT="large_margin"
    - PROJECT="probabilistic_vqvae"
    - PROJECT="sufficient_input_subsets"
    - PROJECT="attribution"
    - PROJECT="cnn_quantization"
    - PROJECT="dql_grasping"
    - PROJECT="state_of_sparsity"
    - PROJECT="neutra"
    - PROJECT="robust_loss"
    - PROJECT="norml"
    - PROJECT="solver1d"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
script:
  - ./$PROJECT/run.sh

