# coding=utf-8
# Copyright 2023 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: conceptor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy=1.23.5
  - pip:
      - accelerate==0.18.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - controlnet-aux==0.0.1
      - cycler==0.11.0
      - diffusers==0.14.0
      - einops==0.6.0
      - filelock==3.9.0
      - fonttools==4.38.0
      - ftfy==6.1.1
      - gensim==4.3.1
      - huggingface-hub==0.12.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - llvmlite==0.39.1
      - lpips==0.1.4
      - matplotlib==3.7.0
      - mypy-extensions==1.0.0
      - nltk==3.8.1
      - numba==0.56.4
      - numpy==1.23.5
      - open-clip-torch==2.15.0
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.7.0.72
      - pandas==1.5.3
      - pillow==9.4.0
      - plotly==5.14.1
      - protobuf==3.20.3
      - pyparsing==3.0.9
      - pyqt5-sip==12.11.0
      - pyre-extensions==0.0.23
      - pyyaml==6.0
      - regex==2022.10.31
      - scikit-learn==1.2.1
      - scikit-learn-extra==0.3.0
      - scipy==1.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.97
      - shap==0.41.0
      - slicer==0.0.7
      - smart-open==6.3.0
      - tenacity==8.2.2
      - threadpoolctl==3.1.0
      - timm==0.6.12
      - tokenizers==0.13.2
      - torch-fidelity==0.3.0
      - torchmetrics==0.11.4
      - torchvision==0.14.1
      - tqdm==4.64.1
      - transformers==4.26.0
      - typing-inspect==0.8.0
      - xformers==0.0.16
