resnet_depth: 50
train_batch_size: 1024
eval_batch_size: 1024
num_train_images: 1281167
num_eval_images: 50000
train_steps: 112590
base_learning_rate: 0.1
iterations_per_loop: 1251
use_tpu: True
num_cores: 8
enable_lars: False
transpose_input: True
precision: 'bfloat16'
num_label_classes: 1001
use_cache: True
use_async_checkpointing: False
image_size: 224
momentum: 0.9
weight_decay: 0.0001
label_smoothing: 0.0
poly_rate: 0.0
skip_host_call: False
num_parallel_calls: 8
dropblock_groups: ''
dropblock_keep_prob: 0.9
dropblock_size: 7
data_format: 'channels_last'
